---
title: "BC-baseline_char_table"
author: "Suzanne Clougher"
date: "10/10/2021"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=FALSE}
# Source prep data to remove the 10 subjects not matched on menopausal status
source("BC-prep_data_calc_score.R")
library(haven)
library(tidyverse)

# duration of oral contraception ? 
# oc <- read_sas("oc_joe.sas7bdat") %>% select(IDENT, totduroc, ppille)

# 1534 subjects in table after removal of low quality spectra and missing data for WCRF score (percentage of aUPF, breastfeeding and waist circumference)
table_char0 <- df.scores %>% select(CODBMB, ID, CT,   # case-control status
         AGE,                   
         BMI, sc.BMI,
         RTHCat1,               # Waist-hip ratio categorical
         MENOPAUSE,             # menopausal status at blood collection
         
         SMK, DIABETE, Life_Alcohol_Pattern_1, ALCOHOL, sc.ALC, BP, 
         
         CO,                    # previous oral contraceptive use
         Trait_Horm,            # menopausal treatment therapy taken 24h before blood collection
         #DURTHSDIAG,            # Duration of use of therapy at date of diagnosis
         DURTHSBMB,             # Duration of use of therapy at blood collection
         #CENTTIMECat1,          # time before centrifugation (?) OMIT not of interest
         FASTING, 
         STOCKTIME,             # Storage time (years)
         BEHAVIOUR,             # Tumour behaviour
         SUBTYPE, 
         #CERB2,                # HER2 receptor OMIT mostly unknown
         ER,                    # Estrogen receptor positive
         PR,                    # Progesterone receptor positive
         SBR, GRADE, STADE, DIAGSAMPLING,
         DIAGSAMPLINGCat1,
         # WCRF score components
         sc.TT,
         sc.PA, # Physical activity
         sc.FV, sc.TDF, sc.UPF, sc.MEAT, sc.SD, # WCRF score diet components
         sc.BFD) # Breastfeeding time for WCRF score

table_char <- table_char0 %>% 
  mutate(AGEdiag = AGE + DIAGSAMPLING) %>%
  mutate_at(vars(-AGE, -AGEdiag, -STOCKTIME, -ALCOHOL, -DURTHSBMB, -CODBMB), as.factor)

# Not sure what to do with this 
# For reviewers comments: get duration of OC use
#table()
#table_char1 <- table_char %>% left_join(oc, by = "IDENT")

# Check how many pairs have duration of OC data
#table_char1$durOC <- ifelse(is.na(table_char1$totduroc), 0, 1)
```

```{r, echo=FALSE}
library(kableExtra)
library(qwraps2)
options(qwraps2_markup = "markdown")

summ <-list(#"Total subjects"                  = list("N"   =   ~ n()),
    
      "Age at blood collection (years)" = list("Mean"     =  ~ mean_sd(AGE, digits = 1)),
       
     "Menopausal status at blood collection" =
         list("Pre-menopausal"   =  ~ n_perc0(MENOPAUSE == 0, digits = 1),
              "Post-menopausal"  =  ~ n_perc0(MENOPAUSE == 1, digits = 1)),
     
     "Follow-up time to cancer diagnosis" =
       list("5 years or less"   =  ~ n_perc0(DIAGSAMPLINGCat1 == 1, digits = 1),
            "More than five years"  =  ~ n_perc0(DIAGSAMPLINGCat1 == 2, digits = 1),
            "Unknown"                 =  ~ n_perc0(is.na(DIAGSAMPLINGCat1), digits = 1)),
       
     "BMI (kg/m2)" =    
        list("18.5 - 24.9"   =  ~ n_perc0(sc.BMI == 0.5, na_rm = T, digits = 1),
             "25-29.9"              =  ~ n_perc0(sc.BMI == 0.25, na_rm = T, digits = 1),
             "<18.5 or >=30"                   =  ~ n_perc0(sc.BMI == 0, na_rm = T, digits = 1)),
             #"Unknown"                 =  ~ n_perc0(is.na(BMICat1), digits = 1)),
      
      "Waist circumference (cm)" =    
        list("<80"   =  ~ n_perc0(sc.TT == 0.5, na_rm = T, digits = 1),
             "80-88"              =  ~ n_perc0(sc.TT == 0.25, na_rm = T, digits = 1),
             ">=88"                   =  ~ n_perc0(sc.TT == 0, na_rm = T, digits = 1)),       
       
     "Waist to hip ratio" =           
        list("< 0.8" = ~ n_perc0(RTHCat1 == 0, na_rm = T, digits = 1),
             "> 0.8" = ~ n_perc0(RTHCat1 == 1, na_rm = T, digits = 1),
             "Unknown" = ~ n_perc0(is.na(RTHCat1), digits = 1)),
       
     "Smoking status" = 
        list("Yes" = ~ n_perc0(SMK == 1, digits = 1),
              "No"  = ~ n_perc0(SMK == 0, digits = 1)),
       
     "Diabetic status"  = 
        list("Yes" = ~ n_perc0(DIABETE == 1, digits = 1),
              "No"  = ~ n_perc0(DIABETE == 0, digits = 1)),
       
     "Lifetime alcohol drinking pattern" =
        list("Non-consumers (0 g/day)"      =  ~ n_perc0(Life_Alcohol_Pattern_1 == 0, na_rm = T, digits = 1),
              "Light consumers (1-10 g/day)" =  ~ n_perc0(Life_Alcohol_Pattern_1 == 1, na_rm = T, digits = 1),
              "Drinkers (>10 g/day)"         =  ~ n_perc0(Life_Alcohol_Pattern_1 == 2, na_rm = T, digits = 1),
              "Unknown"                      =  ~ n_perc0(is.na(Life_Alcohol_Pattern_1), digits = 1)),
     
     "Alcohol intake (g/day)" =
       list("Mean (SD)" = ~ mean_sd(ALCOHOL, digits = 1)),
     
     "Alcohol intake2 (g/day)" =
       list("0" =  ~ n_perc0(sc.ALC == 1, na_rm = T, digits = 1),
            ">0-<14" =  ~ n_perc0(sc.ALC == 0.5, na_rm = T, digits = 1),
            ">14" =  ~ n_perc0(sc.ALC == 0, na_rm = T, digits = 1)),
       
     "Blood pressure" =
      list("Normal tension"  =  ~ n_perc0(BP == 0, na_rm = T, digits = 1),
              "Hypertension"    =  ~ n_perc0(BP == 1, na_rm = T, digits = 1),
              "Unknown"  =  ~ n_perc0(is.na(BP), digits = 1)),
     
     "Previous oral contraceptive use" =
        list("Yes" = ~ n_perc0(CO == 1, digits = 1),
              "No" = ~ n_perc0(CO == 0, digits = 1)),
       
     "Menopause hormone therapy at blood collection" =
        list("Yes" =  ~ n_perc0(Trait_Horm == 1 & MENOPAUSE == 1, digits = 1),
             "No"  =  ~ n_perc0(Trait_Horm == 0 & MENOPAUSE == 1, digits = 1),
             "Unknown"  =  ~ n_perc0(is.na(Trait_Horm) & MENOPAUSE == 1, digits = 1)),
       
     "Duration of use of menopause hormonal treatment at baseline" =
        list("Mean (SD)" =  ~ mean_sd(DURTHSBMB[MENOPAUSE == 1], digits = 1)),
       
     "Fasting status" =
        list("Fasting"     = ~ n_perc0(FASTING == 1, digits = 1),
              "Non-fasting" = ~ n_perc0(FASTING == 0, digits = 1)),
       
     "Biobank storage time (years)" =
        list("Mean (SD)" = ~ mean_sd(STOCKTIME, digits = 1)),
     
     "Physical activity (MET h/day)" =
       list("<9.375" =  ~ n_perc0(sc.PA == 1, na_rm = T, digits = 1),
            "9.375-18.75" =  ~ n_perc0(sc.PA == 0.5, na_rm = T, digits = 1),
            ">18.75" =  ~ n_perc0(sc.PA == 0, na_rm = T, digits = 1)),     
     
     "Fruits and vegetables (g/day)" =
       list(">=400" =  ~ n_perc0(sc.FV == 0.5, na_rm = T, digits = 1),
            "200-400" =  ~ n_perc0(sc.FV == 0.25, na_rm = T, digits = 1),
            ">200" =  ~ n_perc0(sc.FV == 0, na_rm = T, digits = 1)),
     
     "Total fiber (g/day)" =
       list("0" =  ~ n_perc0(sc.TDF == 0.5, na_rm = T, digits = 1),
            ">0-<14" =  ~ n_perc0(sc.TDF == 0.25, na_rm = T, digits = 1),
            ">14" =  ~ n_perc0(sc.TDF == 0, na_rm = T, digits = 1)),
     
     "Percent of total kcal from ultra-processed foods (aUPFs)"  =
       list("Tertile 1" =  ~ n_perc0(sc.UPF == 1, na_rm = T, digits = 1),
            "Tertile 2" =  ~ n_perc0(sc.UPF == 0.5, na_rm = T, digits = 1),
            "Tertile 3" =  ~ n_perc0(sc.UPF == 0, na_rm = T, digits = 1)),
     
     "Total red meat (g/week) and processed meat (g/week)"  =
       list("Red meat <500 and processed meat <21" =  ~ n_perc0(sc.MEAT == 1, na_rm = T, digits = 1),
            "Red meat <500 and processed meat 21-<100" =  ~ n_perc0(sc.MEAT == 0.5, na_rm = T, digits = 1),
            "Red meat >500 and processed meat >=100" =  ~ n_perc0(sc.MEAT == 0, na_rm = T, digits = 1)),
     
     "Total sugar-sweetened drinks (g/day)"  =
       list("0" =  ~ n_perc0(sc.SD == 1, na_rm = T, digits = 1),
            "0-<=250" =  ~ n_perc0(sc.SD == 0.5, na_rm = T, digits = 1),
            ">250" =  ~ n_perc0(sc.SD == 0, na_rm = T, digits = 1)),

      "Exclusively breastfeed over lifetime for a total of"  =
       list("6+ months" =  ~ n_perc0(sc.BFD == 1, na_rm = T, digits = 1),
            ">0-<6 months" =  ~ n_perc0(sc.BFD == 0.5, na_rm = T, digits = 1),
            "Never" =  ~ n_perc0(sc.BFD == 0, na_rm = T, digits = 1))
     )
```

```{r, echo=FALSE}
# By case-control status
status <- table_char %>% group_by(CT) %>% summary_table(summ)
print(status, cnames = c("Controls (N=764)", "Cases (N=770)"))

# By case-control and menopausal status (for reviewers)
status2 <- table_char %>% group_by(CT, MENOPAUSE) %>% summary_table(summ)
print(status2, cnames = c("Pre, controls (N=170)", "Pre, cases (N=173)", 
                     "Post, controls (N=594)", "Post, cases (N=597)"))
# Copy and paste output into table1_bc_ms.Rmd and render to word/pdf etc
```

```{r, echo=FALSE}
# Table of tumor characteristics by menopausal status
summ1 <-
  list("Age at diagnosis" =
      list("Mean (SD)" =  ~ mean_sd(AGEdiag, na_rm = T, digits = 1)),
    
    "Time between sampling and diagnosis" =
      
      list("5 years or less"   =  ~ n_perc0(DIAGSAMPLINGCat1 == 1, na_rm = T, digits = 1),
           "More than 5 years" =  ~ n_perc0(DIAGSAMPLINGCat1 == 2, na_rm = T, digits = 1),
           "Unknown"                 =  ~ n_perc0(is.na(DIAGSAMPLINGCat1), digits = 1)),
    
    "Tumor behavior" =
      
      list("In situ"  = ~ n_perc0(BEHAVIOUR == 2, na_rm = T, digits = 1),
           "Invasive" = ~ n_perc0(BEHAVIOUR == 3, na_rm = T, digits = 1),
           "Unknown"  = ~ n_perc0(is.na(BEHAVIOUR), digits = 1)),
    
    "Subtype" =
      
      list("Lobular"  =  ~ n_perc0(SUBTYPE == 1, na_rm = T, digits = 1),
           "Ductal"   =  ~ n_perc0(SUBTYPE == 2, na_rm = T, digits = 1),
           "Tubular"  =  ~ n_perc0(SUBTYPE == 3, na_rm = T, digits = 1),
           "Mixed"    =  ~ n_perc0(SUBTYPE == 4, na_rm = T, digits = 1),
           "Others"   =  ~ n_perc0(SUBTYPE == 5, na_rm = T, digits = 1),
           "Unknown"  =  ~ n_perc0(is.na(SUBTYPE), digits = 1)),
    
    "Estrogen receptor" =
      
      list("Negative"   =  ~ n_perc0(ER == 0, na_rm = T, digits = 1),
           "Positive"  =  ~ n_perc0(ER == 1, na_rm = T, digits = 1),
           "Unknown"   =  ~ n_perc0(is.na(ER), digits = 1)),
    
    "Progesterone receptor" =
      
      list("Negative"  =  ~ n_perc0(PR == 0, na_rm = T, digits = 1),
           "Positive" =  ~ n_perc0(PR == 1, na_rm = T, digits = 1),
           "Unknown"  =  ~ n_perc0(is.na(PR), digits = 1)),
    
    "Grade" =
      
      list("I"      =  ~ n_perc0(SBR == 1, na_rm = T, digits = 1),
           "II"  =  ~ n_perc0(SBR == 2, na_rm = T, digits = 1),
           "III"   =  ~ n_perc0(SBR == 3, na_rm = T, digits = 1),
           "Unknown"          =  ~ n_perc0(is.na(SBR), digits = 1)),
    
    "Stage" =
      
      list("1"    =  ~ n_perc0(STADE == 1, na_rm = T, digits = 1),
           "2"    =  ~ n_perc0(STADE == 2, na_rm = T, digits = 1),
           "3"    =  ~ n_perc0(STADE == 3, na_rm = T, digits = 1),
           "4"    =  ~ n_perc0(STADE == 4, na_rm = T, digits = 1),
           "Unknown"  =  ~ n_perc0(is.na(STADE), digits = 1))
    
  )
```

```{r, echo=FALSE}
status1 <- table_char %>%  
  summary_table(summ1)
print(status1)

status1_menop <- table_char %>% filter(CT == 1) %>% group_by(MENOPAUSE) %>% 
  summary_table(summ1)
print(status1_menop, cnames = c("Pre-menopausal", "Post-menopausal"))
```


```{r, echo=FALSE}
# Models for p-values for table
# Chi-sq and wilcox test
chisq.test(table_char$CT, table_char$sc.BMI)$p.value
chisq.test(table_char$CT, table_char$sc.TT)$p.value
chisq.test(table_char$CT, table_char$RTHCat1)$p.value
chisq.test(table_char$CT, table_char$SMK)$p.value
chisq.test(table_char$CT, table_char$DIABETE)$p.value
chisq.test(table_char$CT, table_char$Life_Alcohol_Pattern_1)$p.value
chisq.test(table_char$CT, table_char$sc.ALC)$p.value
chisq.test(table_char$CT, table_char$BP)$p.value
chisq.test(table_char$CT, table_char$CO)$p.value
chisq.test(table_char$CT, table_char$Trait_Horm)$p.value
chisq.test(table_char$CT, table_char$FASTING)$p.value
chisq.test(table_char$CT, table_char$sc.PA)$p.value
chisq.test(table_char$CT, table_char$sc.FV)$p.value
chisq.test(table_char$CT, table_char$sc.TDF)$p.value
chisq.test(table_char$CT, table_char$sc.UPF)$p.value
chisq.test(table_char$CT, table_char$sc.MEAT)$p.value
chisq.test(table_char$CT, table_char$sc.SD)$p.value
chisq.test(table_char$CT, table_char$sc.BFD)$p.value
# Wilcox tests not <orking
#wilcox.test(table_char$ALCOHOL ~ table_char$CT, paired = T)$p.value  
#wilcox.test(table_char$DURTHSBMB ~ table_char$CT, paired = T)$p.value
#wilcox.test(table_char$STOCKTIME ~ table_char$CT, paired = T)$p.value

# McNemar test for binaries
mcnemar.test(table_char$CT, table_char$SMK)
mcnemar.test(table_char$CT, table_char$DIABETE)
mcnemar.test(table_char$CT, table_char$CO)

# MHT use only in post-menopausal
table_char.post <- table_char[ table_char$MENOPAUSE == 1, ]
chisq.test(table_char.post$CT, table_char.post$Trait_Horm)$p.value
wilcox.test(table_char.post$DURTHSBMB ~ table_char.post$CT)$p.value

# Pre/post menopausal models
chisq.test(table_char$MENOPAUSE, table_char$DIAGSAMPLINGCat1)$p.value
chisq.test(table_char$MENOPAUSE, table_char$BEHAVIOUR)$p.value
fisher.test(table_char$MENOPAUSE, table_char$SUBTYPE)$p.value
chisq.test(table_char$MENOPAUSE, table_char$ER)$p.value
chisq.test(table_char$MENOPAUSE, table_char$PR)$p.value
chisq.test(table_char$MENOPAUSE, table_char$GRADE)$p.value
fisher.test(table_char$MENOPAUSE, table_char$STADE)$p.value



# Identification of triple negative cases
#sum(table_char$CERB2 == 0 & table_char$ER == 0 & table_char$PR == 0, na.rm = T)
#sum(mtable_char$ER == 0 & table_char$PR == 0, na.rm = T)
```


