---
title: "WCRFAICR score in all E3N"
author: "Suzanne Clougher"
date: "08/06/2021"
output: html_document
---

```{r}
library(ggplot2)
library(haven)
library(tidyverse)
```


```{r}
# Food data
alim <- read_sas("frjour.sas7bdat")  

# Breastfeeding data
bfeed <- read_sas("d_grossesse_20190107_corrections.sas7bdat") %>% rename(ident = IDENT)

# Physical activity data 
physact <- read_sas("physicalact.sas7bdat") %>% rename(ident = IDENT)  

# Fiber data
fiber <- read_sas("nut_fra2.sas7bdat") %>% select(ident, alcool, FIBR, SDF, TDF)  

# Create a single table (containing both cases and controls)
scoredata_all <-  fiber %>%
  left_join(alim, by = "ident") %>% left_join(alim, by = "ident") %>%
  left_join(physact, by = "ident")
dim(scoredata_all)

length(which(is.na(bfeed$allaitement_dureecum)))
```



```{r }
data_xnames_all <- scoredata_all %>%
  rename_at(vars(starts_with('_')), funs(str_replace(., '_', 'x')))
head(data_xnames_all)
```

```{r }
#Calculating intakes necessary for score 
# g/day intake of total fruits & vegetables, red meat, processed meat, sugary drinks, aUPF, total food intake and percentage of aUPF in total food intake
data_xnames_sums_all <- data_xnames_all %>%
  rowwise() %>%
  mutate (fruitveg = sum(x2, x3, x35, x40, x41_2, x41_5, x41_11, x53), #g/day
          Rmeat = sum(x46_3, x46_7, x46_9, x47_2)*7, #g/week
          Pmeat = sum(x19, x36, x37, x41_4, x41_7, x42, x47_6)*7, #g/week
          sugary_drinks = sum(x7, x21), #g/day
          aUPF = sum(x10_4, x10_7, x11_2, x11_3, x11_5, x11_6, x14, x15, x16_3, x16_4, 
                     x16_5, x16_6, x17_4, x17_5, x17_6, x22, x23, x24, x33, x47_1, 
                     x47_5, x47_8, x50, x54, x55, 
                     MG2, MG3, MG4, MG12, MG15, VIN1, VIN2), #g/day
          total_food = 
            sum(x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, 
                x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, 
                x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, 
                x42, x43, x44, x45, x46, x47, x48, x49, x50, x51, x52, x53, x54, 
                x55, x56, x57, x58, x59, 
                SUCRE, EDULC, LAIT, VIN, MG)) %>% #g/day
  mutate (percent_aUPF = (aUPF/total_food) *100) #percent of aUPF in total food intake (g/day)
head(data_xnames_sums_all)
```

```{r }
which(is.na(data_xnames_sums$TotalAPQ3)) #nothing missing
#fruitveg
which(is.na(data_xnames_sums$fruitveg)) #nothing missing
#TDF
which(is.na(data_xnames_sums$TDF)) #nothing missing
#percent_aUPF
which(is.na(data_xnames_sums$percent_aUPF)) #nothing missing


#Rmeat
which(is.na(data_xnames_sums$Rmeat)) #nothing missing
#Pmeat
which(is.na(data_xnames_sums$Pmeat)) #nothing missing
#sugary_drinks
which(is.na(data_xnames_sums$sugary_drinks)) #nothing missing
#ALCOHOL 
which(is.na(data_xnames_sums$alcool)) #nothing missing
#allaitement_dureecum
data_allaitement <- which(is.na(data_xnames_sums$allaitement_dureecum))
```

```{r }

```


```{r }

```

```{r }

```

```{r }

```

